# Generated by Django 5.0.3 on 2024-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.TextField(max_length=255)),
                ('Symbol', models.TextField(max_length=50)),
                ('Country', models.TextField(max_length=100)),
                ('Sector', models.TextField(max_length=100)),
                ('Industry', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'stock_list',
            },
        ),
    ]
